// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZL4-qA3aajwuaDoKwqqper6IJoLCtn_0',
    appId: '1:1098425207745:web:26d3c47109e3a5eac2fd40',
    messagingSenderId: '1098425207745',
    projectId: 'janel-abiya',
    authDomain: 'janel-abiya.firebaseapp.com',
    storageBucket: 'janel-abiya.firebasestorage.app',
    measurementId: 'G-M7K9MKWLDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDGK2c0M3xvLp9SCFzTPqjcMM4z5N8JA',
    appId: '1:1098425207745:android:74fa828cf33ca3a6c2fd40',
    messagingSenderId: '1098425207745',
    projectId: 'janel-abiya',
    storageBucket: 'janel-abiya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsAKAJIf7zSQWaaOEe8R2rResMAIvmyM',
    appId: '1:1098425207745:ios:e4ac98d5da2d2952c2fd40',
    messagingSenderId: '1098425207745',
    projectId: 'janel-abiya',
    storageBucket: 'janel-abiya.firebasestorage.app',
    iosBundleId: 'com.example.janelAbiya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZL4-qA3aajwuaDoKwqqper6IJoLCtn_0',
    appId: '1:1098425207745:web:b50331ad6277e800c2fd40',
    messagingSenderId: '1098425207745',
    projectId: 'janel-abiya',
    authDomain: 'janel-abiya.firebaseapp.com',
    storageBucket: 'janel-abiya.firebasestorage.app',
    measurementId: 'G-0SYWG5ZN60',
  );
}
